### ISSUE TITLE
Display user's game postings in my games

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#10]
## User Story
As a **user**, I would like **to see all my open and scheduled game postings in my personal schedule** so that **I know when I am scheduled to play a game**.

## Detailed Description
A user's game postings must be linked to and displayed in their personal schedule. 

## Tasks
- [x] Get user games #65 #69 #52 
- [x] frontend display of games #106 

## Acceptance Criteria
- [x] Given a schedule request, display the game postings on it (may change due to changing requirements).
- [x] Specific My Games page for user that displays all current games
