### ISSUE TITLE
Navigate to my game postings 

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#11]
## User Story
As a **user**, I would like **to see all the details of a game posting in my schedule on clicking it** **(changed to my games page instead)** so that **I know all the relevant information before leaving for a game**.

## Detailed Description
Users should be able to obtain more information about a game posting in their schedule by clicking it. They should be able to determine the sport, skill level, players, and location of any event they are scheduled to participate in.

- [x] Get games from within a schedule #69 
- [x] Get Schedule endpoint #65 
- [x] Frontend capabilities/user games pages [REFER TO #12  ; UPDATED DESIGN TO NOT SHOW GAMES THRU SCHEDULE]

## Acceptance Criteria
- [x] Given the user clicks on a game, display profiles of all the users.
