### ISSUE TITLE
Display open game postings

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#12]
## User Story
As a **user**, I would like **to see open game postings** so that **I may find games I might be interested in joining**.

## Detailed Description
On the "Games" page, users should be able to see all open game postings by default.

## Acceptance Criteria
- [x] Given **that the user navigates to the games page**, then **the user should be able to see all open game postings by default.**

## Tasks
- [x] Implement basic capability to query DB for all current games #26 
- [x] Allow user to view games from home page #50 
- [x] Return current games endpoint #26
