### ISSUE TITLE
Filter open game postings

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#13]
## User Story
As a **user**, I would like **to filter open game postings by sport, skill level, location, etc.** so that **I may be able to narrow down postings to the ones I am interested in joining**.

## Detailed Description
Users should be able to filter the list of all open game postings by criteria such as the sport, the skill level of the players involved, the location, the date, and the time. 

## Tasks
- [x] Filter games backend endpoint #44 #61 #62 
- [x] User game filters result on home page #100 #110 

## Acceptance Criteria
- [x] Given **a user selects certain filters for games**, then **the database query should return a filtered list of game objects**
