### ISSUE TITLE
Request to join game posting

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#14]
## User Story
As a **user**, I would like **to be able to request to join a game posting** so that **I may play a game that I am interested in**.

## Detailed Description
Every user should be able to send requests to join a specific game posting that they are interested in. This request could be sent via a button click on the game posting.
- [x] join game backend endpoint #51 
- [x] allow viewing of games and users #50 
- [x] Frontend game page #63 

## Acceptance Criteria
- [x] Given **a user click request to join game button**, then **the game creator should receive a notification of the request**
