### ISSUE TITLE
Create, publish, and delete game postings (backend)

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#15]
## User Story
As a **user**, I would like **to be able to create and publish a game posting** so that **I may find other players keen to play the same sport with me**.

## Detailed Description
Every logged-in user should be able to create an open game posting. Users specify the following game information when creating games. 

- Sport
- Desired skill level 
- Location
- Date and time

Users should also be able to delete created game postings.

## Acceptance Criteria
- [x] Given **user completes game creation**, then **the new game should persist in our database**
- [x] Given **user clicks delete game button**, then **the game should be deleted from the database**

## Tasks
- [x] Basic create and delete game capability #25
