### ISSUE TITLE
View other users

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#17]
## User Story
As a **user**, I would like **to view other users** so that **I may find like-minded players with whom to play my favorite sports**.

## Detailed Description
On navigating to the "People" page, every user should be able to see a list of other users. This list should be filtered by default to exclude users outside a certain distance radius. 

## Tasks
- [x] Get users backend endpoint #48 
- [x] View other users from home page itself #50 

## Acceptance Criteria
- [x] Given **a user navigates to the people page**, then **a list of users should be displayed**
