### ISSUE TITLE
Filter users

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#18]
## User Story
As a **user**, I would like **to filter the user list by distance, preferred sports, and skill level** so that **I may find players who best match my preferences**.

## Detailed Description
Every user should be able to filter the user list on the "People" page by the following criteria.

- Preferred sports
- Skill level
- Distance radius

## Tasks
- [x] Get users backend endpoint (with query parameters) #48 #60 
- [x]  Specific user filters #84 #87
## Acceptance Criteria
- [x] Given **a user navigates to the people page**, then **optional filter dropdowns should be visible and selectable**
- [x] Given **a user selects certain filters on the people page**, then **the displayed users should be filtered as specified**
