### ISSUE TITLE
Game Postings

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#3]
## Epic

Description and User Benefit:
A game posting is a public announcement of a game to be held. Users can create public game postings indicating the sport, the total number of required players, the desired skill level of participants, the location, and preferred date and time. Users should also be able to search for open game postings and join games they are interested in.

User Actions:

- The user should be able to create and publish a new game posting with all the necessary information.
- The user should be able to accept requests from other users to join a specific game posting.
- The user should be able to view open game postings. 
- The user should be able to request to join games.
- The user should be able to filter open game postings by criteria such as sport, skill level, distance, date, and time.

## User Stories
- [x] Display open game postings #12 
- [x] Filter open game postings #13 
- [x] Edit game postings #46 
- [x] Request to join an open game posting #14 
- [x] Create and publish a new game posting #15 
- [x] Accept requests to join game postings #16
