### ISSUE TITLE
Complete Analysis Description - UML Diagrams

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#36]
## User Story
As a **developer**, I would like **to create UML diagrams** so that **we encapsulate our application's functional requirements in an easily understood manner**.

## Detailed Description
Create the following UML diagrams.

1. Use Case diagram
2. Activity diagrams for different actors
3. Class diagram
4. Sequence diagrams
5. State Machine diagrams

## Acceptance Criteria
- [x] Complete Use Case diagram
- [x] Complete Activity diagrams
- [x] Complete Class diagram
- [x] Complete Sequence diagrams
- [x] Complete State Machine diagrams

## Tasks

- [x] Use Case diagram
- [x] Activity diagrams
- [x] Class diagram
- [x] Sequence diagrams
- [x] State Machine diagrams
