### ISSUE TITLE
Complete Architecture Description

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#37]
## User Story
As a **developer**, I would like **to complete an architecture description of our application** so that **we may describe and document the non-functional requirements of the app, the components of the architecture, and how these components are organized**.

## Detailed Description
Create 3 high-level architecture diagrams (one for each architecture level and for the second level focus on the most complex components) for our application that conforms to the patterns we chose.

The 3 levels are as follows.
1. Across components (application landscape patterns)
2. Within components (application structure patterns)
3. For the UI components (user interface patterns)

Write up short descriptions of each level as well.

## Acceptance Criteria
- [x] Application landscape diagram and description completed
- [x] Application structure diagrams and description completed
- [x] User interface patterns diagrams and description completed
 
## Tasks

- [x] Application landscape diagram and description
- [x] Application structure diagrams and description
- [x] User interface patterns diagrams and description
