### ISSUE TITLE
Sign up to create new account

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#6]
## User Story
As a **user**, I would like **to sign up** so that **I may create a new user account and use the app's various features**.

## Detailed Description
A user must sign up to create a new account. No user can create a game posting, request to join a game, or chat with other users unless they have an account. 

The signup flow should be triggered by a button click. It must then set up a user's username and password for future authentication. Once the user has finished signup, they should be automatically logged in.

## Tasks
- [x] Set up react front end for signup #23
- [x] Set up initial node backend

## Acceptance Criteria
- [x] Given **a user clicks sign up**, then **the user should see a form to register the sign up information**
- [x] Given **a user enters an invalid/used username or invalid password**, then **they should be prompted to change their signup information**
- [x] Given **a user completes signup successfully**, then **the user's authentication data must be saved and the user should be logged in**
