### ISSUE TITLE
Log in to user account

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#7]
## User Story
As a **user**, I would like **to log in to my user account** so that **I may view and edit my profile, create and join game postings, and interact with other users**.

## Detailed Description
A user must be able to log in to their user account once it has been created. This log in must be authenticated by the user's username and password as defined during sign up. Logging in allows users to then partake in all the application's features such as the creation of game postings, chat, etc.

The login flow should be triggered by a button click. Once a user is logged in, the login button should be replaced by a logout button.

## Tasks
- [x] Be able to get current user logged in #85 

## Acceptance Criteria
- [x] Given **the user enters a valid username and password**, **the user should be logged into the app**
- [x] Given **the user enters an invalid username or password**, **the user should not be allowed to log in to the app**
