### ISSUE TITLE
Edit user profile

### ISSUE THREAD

**Issue by rsukumar75** [cs130-w21/11#8]
## User Story
As a **user**, I would like **to edit my profile** so that **I may update my schedule, sport preferences, skill level, and location among other miscellaneous details**.

## Detailed Description
Every user must be able to edit their profile information at any time. Users must be logged in to edit their profile. 

Furthermore, the user profile must allow users to set the following fields.

- Name
- Profile Picture
- Email Address/Social Media 
- Location
- Personal schedule
- Preferred sports
- Skill level for each sport

## Tasks
- [x] Update user backend endpoint #32 
- [x] Create user profile #31 
- [x] Update/delete schedule endpoint #68 #67 
- [x] Update user endpoint #79 

## Acceptance Criteria
- [x] Given **a user click edit profile button**, then **the user should see a form to update their profile information**
- [x] Given **a user submits a profile update**, then **the changes to the user's profile should persist in the database**
