### ISSUE TITLE
Frontend changes: game participants, user games

### ISSUE THREAD

**Issue by akcode101** [cs130-w21/11#95]
## User Story
As a **user**, I would like to be able to have access to the**create game participants** and **user games** pages!.

## Detailed Description
- [x] Game participants frontend functionality, tied in with search updates #112 
- [x] Ability to join and leave games, user-game associations related endpoints #51 #52 
- [x] Frontend updates for stylistic purposes #106 

## Acceptance Criteria
- [x] Users will be able to join games, and it will be able to be viewed on the frontend
